---
- name: AWS instance creation
  hosts: localhost
  gather_facts: no
  vars:
    ec2_region: us-east-1
    ec2_name_prefix: Hyperion
    ami_name: RHEL-7.6_HVM_GA-20181017-x86_64-0-Hourly2-GP2
    sec_group_id: sg-0706617a47b119ccb
    subnet_id: subnet-c8f8efa1
    instance_type: t2.micro
    roletag: demo_server
    ec2_counter: 2
    extra_volume_size: 5
  tags:
    - create
  tasks:
    - name: Get available VPC ID for {{ ec2_name_prefix }}-vpc
      amazon.aws.ec2_vpc_net_info:
        filters:
          "tag:Name": "{{ ec2_name_prefix }}-vpc"
        region: "{{ ec2_region }}"
      register: vpc_net_facts
    
    - name: Get the SG ID for {{ ec2_name_prefix }}-sg
      amazon.aws.ec2_group_info:
        filters:
          vpc-id: "{{ vpc_net_facts.vpcs[0].id }}"
          group-name: "{{ ec2_name_prefix }}-sg"
        region: "{{ ec2_region }}"
      register: sg_net_facts
      ignore_errors: yes
    
    - name: Get the subnet IDs for {{ ec2_name_prefix }}-vpc
      amazon.aws.ec2_vpc_subnet_info:
        region: "{{ ec2_region }}"
        filters:
          vpc-id: "{{ vpc_net_facts.vpcs[0].id }}"
      register: subnet_info
      ignore_errors: yes
      when: vpc_net_facts is defined
    
    - name: "Find current, region-specific AMI."
      amazon.aws.ec2_ami_info:
        region: "{{ ec2_region }}"
        filters:
          name: "{{ ami_name }}"
      register: found_amis

    - name: "Set AMI value"
      set_fact:
        book_ami: "{{ found_amis.images | selectattr('name', 'defined') | sort(attribute='creation_date') | last }}"
      when: found_amis.images is defined

    - name: Setup instances for testing
      amazon.aws.ec2:
        key_name: "{{ aws_key }}"
        instance_type: "{{ instance_type }}"
        image: "{{ book_ami.image_id }}"
        region: "{{ ec2_region }}"
        vpc_subnet_id: "{{ subnet_info.subnets[0].id|default(subnet_id) }}"
        group_id: "{{ sg_net_facts.security_groups[0].group_id|default(sec_group_id) }}"
        wait: yes
        wait_timeout: 500
        assign_public_ip: yes
        count: "{{ ec2_counter }}"
        volumes:
          - device_name: /dev/xvdb
            volume_size: "{{ extra_volume_size }}"
            delete_on_termination: true
        count_tag:
          Name: "{{ ec2_name_prefix }} RHEL server"
        instance_tags:
          Role: "{{ roletag }}"
          Platform: RHEL
          Name: "{{ ec2_name_prefix }} RHEL server"
          Inventory: "{{ ec2_name_prefix }}"
          Stage: "instantiated"
      register: ec2
    
    - debug:
        msg: "{{ ec2.tagged_instances }}"
    
    - name: "Wait for connection on all hosts."
      wait_for:
        host: "{{ item.private_ip }}"
        port: 22
        timeout: 300
      loop: "{{ ec2.tagged_instances }}"
  
- name: AWS instances termination
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    ec2_region: us-east-1
    roletag: demo_server
    instance_ids: []
    vpc_id: vpc-852620ec
  tags:
    - terminate
    - never
  tasks:
    - name: Get the VPC ID for {{ ec2_name_prefix }}-vpc
      amazon.aws.ec2_vpc_net_info:
        filters:
          "tag:Name": "{{ ec2_name_prefix }}-vpc"
        region: "{{ ec2_region }}"
      register: vpc_net_facts
    
    - name: Set ec2_vpc_id value
      set_fact:
        ec2_vpc_id: "{{ vpc_net_facts.vpcs[0].id|default(vpc_id) }}"
    
    - name: Gather information about any instance with a tag key Role
      ec2_instance_info:
        region: "{{ ec2_region }}"
        filters:
          "tag:Role": "{{ roletag }}"
          "vpc-id": "{{ ec2_vpc_id }}"
      register: ec2

    - name: build a list of instances to terminate
      set_fact:
        instance_ids: "{{ instance_ids }} + [ '{{ item.instance_id }}' ]"
      with_items: "{{ ec2.instances }}"

    - name: AWS instances termination
      amazon.aws.ec2:
        instance_ids: "{{ instance_ids }}"
        region: "{{ ec2_region }}"
        state: absent
        wait: yes
...
