---
# ec2 security group defs
rules:
  ssh:
    ports:
      - proto: tcp
        to_port: 22
        from_port: 22
        cidr_ip: 0.0.0.0/0
  http:
    ports:
      - proto: tcp
        to_port: 22
        from_port: 22
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        to_port: 80
        from_port: 80
        cidr_ip: 0.0.0.0/0
  https:
    ports:
      - proto: tcp
        to_port: 22
        from_port: 22
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        to_port: 80
        from_port: 80
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        to_port: 443
        from_port: 443
        cidr_ip: 0.0.0.0/0
  wls:
    ports:
      - proto: tcp
        to_port: 22
        from_port: 22
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        to_port: 7002
        from_port: 7001
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        to_port: 8002
        from_port: 8001
        cidr_ip: 0.0.0.0/0        
      - proto: tcp
        to_port: 5456
        from_port: 5456
        cidr_ip: 0.0.0.0/0
...
